version: "1"

services:
    mssql:
        image: mcr.microsoft.com/mssql/server
        environment:
          - SA_PASSWORD=Pass@word
          - ACCEPT_EULA=Y
        ports:
          - "1433:1433"
